name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      - name: Build
        run: |
          set -ex
          git clone --depth=1 https://github.com/${GITHUB_REPOSITORY}
          cd $(basename ${GITHUB_REPOSITORY})
          go vet
          go test -v -cover
          go build -v -race
          (cd cmd/fastdig && go build -v)
          (cd cmd/dns && go build -v)
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.61.0
          ./bin/golangci-lint run
